// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const USER_LOGOUT = "USER_LOGOUT"
export const IS_LOADING = "IS_LOADING"
export const NOT_LOADING = "NOT_LOADING"
// LOGIN

// REGISTER
export const ON_USER_REGISTER = "ON_USER_REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"
// REGISTER